---

- name: Create Prometheus Node Exporter directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_node_exporter.user }}"
    group: "{{ prometheus_node_exporter.group }}"
    mode: 0750
  with_items:
    - "{{ prometheus_node_exporter.path.install }}"
    - "{{ prometheus_node_exporter.path.install }}/bin"
    - "{{ prometheus_node_exporter.path.log }}"

- name: Copy wrapper shell script
  become: yes
  copy:
    src: prometheus_wrapper
    dest: "{{ prometheus_node_exporter.path.install }}/bin/prometheus_wrapper"
    owner: "{{ prometheus_node_exporter.user }}"
    group: "{{ prometheus_node_exporter.group }}"
    mode: 0755

- stat:
    path: "{{ prometheus_node_exporter.download_dest }}/{{ prometheus_node_exporter.download_url.split('/')[-1] }}"
  register: download_tar

- name: Download Prometheus Node Exporter tarball
  become: yes
  get_url:
    url: "{{ prometheus_node_exporter.download_url }}"
    dest: "{{ prometheus_node_exporter.download_dest }}"
    checksum: "{{ prometheus_node_exporter.checksum }}"
  when: download_tar.stat.exists == False

- name: Untar Prometheus Node Exporter tarball
  become: yes
  unarchive:
    src: "{{ prometheus_node_exporter.download_dest }}/{{ prometheus_node_exporter.download_url.split('/')[-1] }}"
    dest: "{{ prometheus_node_exporter.path.install }}"
    owner: "{{ prometheus_node_exporter.user }}"
    group: "{{ prometheus_node_exporter.user }}"
    remote_src: True
  when: download_tar.stat.exists == False

- name: Ensure Prometheus Node Exporter directory does not exist
  become: yes
  file:
    path: "{{ prometheus_node_exporter.path.install }}/prometheus_node_exporter/"
    state: absent
  when: download_tar.stat.exists == False

- name: Move Prometheus Node Exporter directory to destination
  become: yes
  become_user: "{{ prometheus_node_exporter.user }}"
  command: "mv {{ prometheus_node_exporter.path.install }}/{{ prometheus_node_exporter.download_url.split('/')[-1].rsplit('.',2)[0] }} {{ prometheus_node_exporter.path.install }}/prometheus_node_exporter"
  when: download_tar.stat.exists == False

- name: Make Prometheus Node Exporter a service
  become: yes
  template:
    dest: /etc/init.d/prometheus-node-exporter
    mode: 0775
    src: prometheus_node_exporter.sysvinit.j2

- name: Make Prometheus Node Exporter service start on boot
  become: yes
  service:
    name: prometheus-node-exporter
    enabled: yes
    state: started
  when: prometheus_node_exporter.start_on_boot
